/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSlotsRouteImport } from './routes/_app/slots'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppReceivablesRouteImport } from './routes/_app/receivables'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppPendingPaymentsRouteImport } from './routes/_app/pending-payments'
import { Route as AppPayablesRouteImport } from './routes/_app/payables'
import { Route as AppPacientesRouteImport } from './routes/_app/pacientes'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppHoursRouteImport } from './routes/_app/hours'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChartAccountsRouteImport } from './routes/_app/chart-accounts'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBalanceRouteImport } from './routes/_app/balance'
import { Route as AppPacientesPacienteIdRouteImport } from './routes/_app/pacientes.$pacienteId'
import { Route as AppConfigUsuariosRouteImport } from './routes/_app/config.usuarios'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlotsRoute = AppSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingPaymentsRoute = AppPendingPaymentsRouteImport.update({
  id: '/pending-payments',
  path: '/pending-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPayablesRoute = AppPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppHoursRoute = AppHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChartAccountsRoute = AppChartAccountsRouteImport.update({
  id: '/chart-accounts',
  path: '/chart-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBalanceRoute = AppBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesPacienteIdRoute = AppPacientesPacienteIdRouteImport.update({
  id: '/$pacienteId',
  path: '/$pacienteId',
  getParentRoute: () => AppPacientesRoute,
} as any)
const AppConfigUsuariosRoute = AppConfigUsuariosRouteImport.update({
  id: '/config/usuarios',
  path: '/config/usuarios',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/balance': typeof AppBalanceRoute
  '/categories': typeof AppCategoriesRoute
  '/chart-accounts': typeof AppChartAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/hours': typeof AppHoursRoute
  '/overview': typeof AppOverviewRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/payables': typeof AppPayablesRoute
  '/pending-payments': typeof AppPendingPaymentsRoute
  '/plans': typeof AppPlansRoute
  '/receivables': typeof AppReceivablesRoute
  '/services': typeof AppServicesRoute
  '/slots': typeof AppSlotsRoute
  '/config/usuarios': typeof AppConfigUsuariosRoute
  '/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/balance': typeof AppBalanceRoute
  '/categories': typeof AppCategoriesRoute
  '/chart-accounts': typeof AppChartAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/hours': typeof AppHoursRoute
  '/overview': typeof AppOverviewRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/payables': typeof AppPayablesRoute
  '/pending-payments': typeof AppPendingPaymentsRoute
  '/plans': typeof AppPlansRoute
  '/receivables': typeof AppReceivablesRoute
  '/services': typeof AppServicesRoute
  '/slots': typeof AppSlotsRoute
  '/config/usuarios': typeof AppConfigUsuariosRoute
  '/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/_app/balance': typeof AppBalanceRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/chart-accounts': typeof AppChartAccountsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hours': typeof AppHoursRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/pacientes': typeof AppPacientesRouteWithChildren
  '/_app/payables': typeof AppPayablesRoute
  '/_app/pending-payments': typeof AppPendingPaymentsRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/receivables': typeof AppReceivablesRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/slots': typeof AppSlotsRoute
  '/_app/config/usuarios': typeof AppConfigUsuariosRoute
  '/_app/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/auth'
    | '/balance'
    | '/categories'
    | '/chart-accounts'
    | '/dashboard'
    | '/hours'
    | '/overview'
    | '/pacientes'
    | '/payables'
    | '/pending-payments'
    | '/plans'
    | '/receivables'
    | '/services'
    | '/slots'
    | '/config/usuarios'
    | '/pacientes/$pacienteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/auth'
    | '/balance'
    | '/categories'
    | '/chart-accounts'
    | '/dashboard'
    | '/hours'
    | '/overview'
    | '/pacientes'
    | '/payables'
    | '/pending-payments'
    | '/plans'
    | '/receivables'
    | '/services'
    | '/slots'
    | '/config/usuarios'
    | '/pacientes/$pacienteId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/agendar'
    | '/auth'
    | '/_app/balance'
    | '/_app/categories'
    | '/_app/chart-accounts'
    | '/_app/dashboard'
    | '/_app/hours'
    | '/_app/overview'
    | '/_app/pacientes'
    | '/_app/payables'
    | '/_app/pending-payments'
    | '/_app/plans'
    | '/_app/receivables'
    | '/_app/services'
    | '/_app/slots'
    | '/_app/config/usuarios'
    | '/_app/pacientes/$pacienteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/slots': {
      id: '/_app/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AppSlotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receivables': {
      id: '/_app/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending-payments': {
      id: '/_app/pending-payments'
      path: '/pending-payments'
      fullPath: '/pending-payments'
      preLoaderRoute: typeof AppPendingPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payables': {
      id: '/_app/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof AppPayablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hours': {
      id: '/_app/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof AppHoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart-accounts': {
      id: '/_app/chart-accounts'
      path: '/chart-accounts'
      fullPath: '/chart-accounts'
      preLoaderRoute: typeof AppChartAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/balance': {
      id: '/_app/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AppBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$pacienteId': {
      id: '/_app/pacientes/$pacienteId'
      path: '/$pacienteId'
      fullPath: '/pacientes/$pacienteId'
      preLoaderRoute: typeof AppPacientesPacienteIdRouteImport
      parentRoute: typeof AppPacientesRoute
    }
    '/_app/config/usuarios': {
      id: '/_app/config/usuarios'
      path: '/config/usuarios'
      fullPath: '/config/usuarios'
      preLoaderRoute: typeof AppConfigUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPacientesRouteChildren {
  AppPacientesPacienteIdRoute: typeof AppPacientesPacienteIdRoute
}

const AppPacientesRouteChildren: AppPacientesRouteChildren = {
  AppPacientesPacienteIdRoute: AppPacientesPacienteIdRoute,
}

const AppPacientesRouteWithChildren = AppPacientesRoute._addFileChildren(
  AppPacientesRouteChildren,
)

interface AppRouteChildren {
  AppBalanceRoute: typeof AppBalanceRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppChartAccountsRoute: typeof AppChartAccountsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHoursRoute: typeof AppHoursRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPacientesRoute: typeof AppPacientesRouteWithChildren
  AppPayablesRoute: typeof AppPayablesRoute
  AppPendingPaymentsRoute: typeof AppPendingPaymentsRoute
  AppPlansRoute: typeof AppPlansRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSlotsRoute: typeof AppSlotsRoute
  AppConfigUsuariosRoute: typeof AppConfigUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBalanceRoute: AppBalanceRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppChartAccountsRoute: AppChartAccountsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHoursRoute: AppHoursRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPacientesRoute: AppPacientesRouteWithChildren,
  AppPayablesRoute: AppPayablesRoute,
  AppPendingPaymentsRoute: AppPendingPaymentsRoute,
  AppPlansRoute: AppPlansRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppServicesRoute: AppServicesRoute,
  AppSlotsRoute: AppSlotsRoute,
  AppConfigUsuariosRoute: AppConfigUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AgendarRoute: AgendarRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
